<?php
/// การตั้งค่าเกี่ยวกับ bot ใน LINE Messaging API
define('LINE_MESSAGE_CHANNEL_ID',getenv('LINE_MESSAGE_CHANNEL_ID'));
define('LINE_MESSAGE_CHANNEL_SECRET',getenv('LINE_MESSAGE_CHANNEL_SECRET'));
define('LINE_MESSAGE_ACCESS_TOKEN',getenv('LINE_MESSAGE_ACCESS_TOKEN'));
?>